version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: flash_postgres
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: flash_sale_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: flash_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flash_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata: